# Generated by Django 4.2.5 on 2023-09-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=50)),
                ('time_stamp', models.DateTimeField(blank=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
